openapi: 3.2.0
info:
  title: Ordoro API Documentation Authenticated API
  description: '# Introduction


    The Ordoro API can be used to access data or integrate to add functionality to Ordoro.'
  contact: {}
  version: '1.0'
servers:
- url: https://api.ordoro.com/
  variables: {}
tags:
- name: Authenticated
  description: ''
paths:
  /authenticated/:
    get:
      tags:
      - Authenticated
      summary: Check Authentication Status
      description: ''
      operationId: Authenticated_GET
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                title: Authenticated Response Schema
                type: object
                properties:
                  success:
                    type: boolean
                required:
                - success
      deprecated: false
